const ACTION_TYPES = {
  CLEAR_ERROR: 'CLEAR_ERROR',

  TOGGLE_THEME: 'TOGGLE_THEME',

  SHOW_SIGN_IN: 'SHOW_SIGN_IN',
  HIDE_SIGN_IN: 'HIDE_SIGN_IN',

  SHOW_SIDEBAR: 'SHOW_SIDEBAR',
  HIDE_SIDEBAR: 'HIDE_SIDEBAR',

  SHOW_SEARCHBAR: 'SHOW_SEARCHBAR',
  HIDE_SEARCHBAR: 'HIDE_SEARCHBAR',


  AUTH_REQUEST: 'AUTH_REQUEST',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_ERROR: 'AUTH_ERROR',
  AUTH_CLEAR_ERROR: 'AUTH_CLEAR_ERROR',
  AUTH_EXIT: 'AUTH_EXIT',

  TOGGLE_POPULAR_CAROUSEL: 'TOGGLE_POPULAR_CAROUSEL',
  TOGGLE_NEW_CAROUSEL: 'TOGGLE_NEW_CAROUSEL',
  TOGGLE_HOT_NEW_CAROUSEL: 'TOGGLE_HOT_NEW_CAROUSEL',

  GET_MANGA: 'GET_MANGA',
  GET_MANGA_REQUEST: 'GET_MANGA_REQUEST',
  GET_MANGA_SUCCESS: 'GET_MANGA_SUCCESS',
  GET_MANGA_ERROR: 'GET_MANGA_ERROR',

  GET_MANGA_CATALOG: 'GET_MANGA_CATALOG',
  GET_MANGA_CATALOG_REQUEST: 'GET_MANGA_CATALOG_REQUEST',
  GET_MANGA_CATALOG_SUCCESS: 'GET_MANGA_CATALOG_SUCCESS',
  GET_MANGA_CATALOG_ERROR: 'GET_MANGA_CATALOG_ERROR',

  GET_MANGA_SEARCH: 'GET_MANGA_SEARCH',
  GET_MANGA_SEARCH_REQUEST: 'GET_MANGA_SEARCH_REQUEST',
  GET_MANGA_SEARCH_SUCCESS: 'GET_MANGA_SEARCH_SUCCESS',
  GET_MANGA_SEARCH_ERROR: 'GET_MANGA_SEARCH_ERROR',
  CLEAR_MANGA_SEARCH: 'CLEAR_MANGA_SEARCH',

  GET_MANGA_COVERS: 'GET_MANGA_COVERS',
  GET_MANGA_COVERS_REQUEST: 'GET_MANGA_COVERS_REQUEST',
  GET_MANGA_COVERS_SUCCESS: 'GET_MANGA_COVERS_SUCCESS',
  GET_MANGA_COVERS_ERROR: 'GET_MANGA_COVERS_ERROR',

  GET_CHAPTER: 'GET_CHAPTER',
  GET_CHAPTER_REQUEST: 'GET_CHAPTER_REQUEST',
  GET_CHAPTER_SUCCESS: 'GET_CHAPTER_SUCCESS',
  GET_CHAPTER_ERROR: 'GET_CHAPTER_ERROR',

  GET_CHAPTERS: 'GET_CHAPTERS',
  GET_CHAPTERS_REQUEST: 'GET_CHAPTERS_REQUEST',
  GET_CHAPTERS_SUCCESS: 'GET_CHAPTERS_SUCCESS',
  GET_CHAPTERS_ERROR: 'GET_CHAPTERS_ERROR',

  GET_CHAPTER_PAGES: 'GET_CHAPTER_PAGES',
  GET_CHAPTER_PAGES_REQUEST: 'GET_CHAPTER_PAGES_REQUEST',
  GET_CHAPTER_PAGES_SUCCESS: 'GET_CHAPTER_PAGES_SUCCESS',
  GET_CHAPTER_PAGES_ERROR: 'GET_CHAPTER_PAGES_ERROR',

  GET_NEXT_CHAPTER_ID: 'GET_NEXT_CHAPTER_ID',
  GET_NEXT_CHAPTER_ID_REQUEST: 'GET_NEXT_CHAPTER_ID_REQUEST',
  GET_NEXT_CHAPTER_ID_SUCCESS: 'GET_NEXT_CHAPTER_ID_SUCCESS',
  GET_NEXT_CHAPTER_ID_ERROR: 'GET_NEXT_CHAPTER_ID_ERROR',

  GET_FIRST_CHAPTER_ID: 'GET_FIRST_CHAPTER_ID',
  GET_FIRST_CHAPTER_ID_REQUEST: 'GET_FIRST_CHAPTER_ID_REQUEST',
  GET_FIRST_CHAPTER_ID_SUCCESS: 'GET_FIRST_CHAPTER_ID_SUCCESS',
  GET_FIRST_CHAPTER_ID_ERROR: 'GET_FIRST_CHAPTER_ID_ERROR',
};

export default ACTION_TYPES;
