const ACTION_TYPES = {
  CLEAR_ERROR: 'CLEAR_ERROR',

  TOGGLE_THEME: 'TOGGLE_THEME',

  SHOW_SIGN_IN: 'SHOW_SIGN_IN',
  HIDE_SIGN_IN: 'HIDE_SIGN_IN',

  SHOW_SIDEBAR: 'SHOW_SIDEBAR',
  HIDE_SIDEBAR: 'HIDE_SIDEBAR',


  AUTH_REQUEST: 'AUTH_REQUEST',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_ERROR: 'AUTH_ERROR',
  AUTH_CLEAR_ERROR: 'AUTH_CLEAR_ERROR',
  AUTH_EXIT: 'AUTH_EXIT',

  TOGGLE_POPULAR_CAROUSEL: 'TOGGLE_POPULAR_CAROUSEL',
  TOGGLE_NEW_CAROUSEL: 'TOGGLE_NEW_CAROUSEL',
  TOGGLE_HOT_NEW_CAROUSEL: 'TOGGLE_HOT_NEW_CAROUSEL',

  GET_MANGA_REQUEST:'GET_MANGA_REQUEST',
  GET_MANGA_SUCCESS:'GET_MANGA_SUCCESS',
  GET_MANGA_ERROR:'GET_MANGA_ERROR',
};

export default ACTION_TYPES;
