FROM node:16.15.1-alpine3.15

ARG NODE_ENV="development"

RUN mkdir /server

WORKDIR /server

COPY package.json ./

COPY yarn.lock ./

RUN yarn global add nodemon

RUN yarn global add sequelize-cli

RUN yarn install

COPY . .

CMD ./start-dev.sh
