FROM node:16.15.1-alpine3.15

ARG NODE_ENV="development"

RUN mkdir /server

RUN mkdir -p /var/www/html/images

WORKDIR /server

COPY package.json ./

COPY yarn.lock ./

RUN yarn global add nodemon

RUN yarn global add sequelize-cli

RUN yarn install

RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . .

EXPOSE 3000

CMD ./start.sh
